### ISSUE TITLE
"User Map" layout breaks on toggling maximized window

### ISSUE THREAD

**Issue by sooqua** [worron/redflat#49]
![Peek 2019-08-18 18-24](https://user-images.githubusercontent.com/4979209/63226689-ac115780-c1e5-11e9-8c34-d82266c4ca88.gif)
You can see the size resets, that doesn't happen on "Right Tile" layout, for example, but worst of all is when you create a custom layout using Modkey+F2 such as two windows side by side and one at the bottom, it resets to a pretty terrible mess if you try to maximize the bottom window.

**Comment by worron** [comment]
Unfortunately it's by design. Manual layout is more complex than "Right Tile" and storing size scheme will be pretty difficult task. So every time window leave tiling mode (maximize, floating, hide, close etc.) its size setting destroyed. I admit it does not seems right, but afraid it will not be fixed in the nearest future.

Awesome isn't designed for manual tiling and my attempt to implement it was not fully successful as you can see. But it's pity to throw out from my config because of some effort I put into. Just keep in mind, this 'usermap' layout is more like proof of concept not very relaible for daily use.

**Comment by sooqua** [comment]
I see. It kinda sucks we can't get awesome to be actually **_awesome_**, although this config gets really close. Thanks nonetheless.
