### ISSUE TITLE
Qlaunch does not accept any input (mouse and keyboard)

### ISSUE THREAD

**Issue by iddm** [worron/redflat#6]
The quick-app launcher does not accept any input but it worked okay 2 years ago. For example, mouse hovering over items, nor clicking the items via mouse buttons, nor keyboard up/down does not work, only `Enter` gets handled.

**Comment by worron** [comment]
You can check all keys for current widget by pressing `mod4+F1` (with holding mod key) while widget is active. What can you see with this tip popup on your installation?

Sorry, mouse buttons will not work any way. I just do not bother to make mouse control for this kind of widget since don't feel like it's necessary feature.

**Comment by iddm** [comment]
Now I see the keys are "Mod + i" and "Mod + k", however, I remember they were just `Up` and `Down` earlier. Did you change this?

**Comment by worron** [comment]
Yes, I'm. Just edit your `keys-config.lua` to turn it back.

**Comment by iddm** [comment]
Thanks :)
